import React, { useState, useEffect } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const list1 = [
  {
    url: '/c4/c4-1.png',
    txt: "Exchange tokens of any chains at one place"
  },
  {
    url: '/c4/c4-2.png',
    txt: "No token listing requirements"
  },
  {
    url: '/c4/c4-3.png',
    txt: "No centralized human intervention with token deposit/withdraw"
  },
  {
    url: '/c4/c4-4.png',
    txt: "Non-custodian, fully transparent with users funds"
  }
]

const partnerList = function() {
  return Array(8).fill(8).map((item, index) => {
    return "/partner/zkp" + (index + 1) + '.png'
  })
}()

const c7list = [
  {
    url: '/c7/c71.png',
    title: 'Discord Community',
    desc: 'Get involved with our discord community server'
  },
  {
    url: '/c7/c72.png',
    title: 'Twitter',
    desc: 'Follow @ZKCross for the latest news and updates across the system.'
  },
  {
    url: '/c7/c73.png',
    title: 'Telegram',
    desc: 'chat with the worldwide community on Telegram.'
  },
  {
    url: '/c7/c74.png',
    title: 'Medium',
    desc: 'post your thinking on ZKCross and connect with millions of readers.'
  },
]

export default function Home() {

  const [navList, setNavList] = useState([
    {
      title: "About",
      selected: false,
      id: "#about"
    },
    {
      title: "Roadmap",
      selected: false,
      id: "#roadmap"
    },
    {
      title: "Products",
      selected: false,
      id: "#products"
    },
    {
      title: "Home",
      selected: true,
      id: "#home"
    }
  ])

  // function handleResize(e) {
  //   console.log('eee>', e)
  // }

  const [isMobile, setIsMobile] = useState(false)

  useEffect(() => {
    // window.addEventListener('resize', handleResize)
    setIsMobile(window.innerWidth < 834)
  })

  return (
    <div className={styles.container}>
      <Head className={styles.head}>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no" />
        <link rel="icon" href="/favicon.ico" />
        <link href=" https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet" />
      </Head>

      <div className={styles.header}>
        <div className={styles.logo}>
          <img alt="" src="/logo.png" />
        </div>
        <div className={styles.navigator}>
          <div className={styles.launch}>Launch test</div>
          {
            navList.map((item, index) => {
              return (
                <a href={item.id}
                  key={item.id}
                  className={item.selected ? styles.active : ''}
                  onClick={
                    () => {
                      const lst = navList.map((nav, idx) => {
                        return {
                          ...nav,
                          selected: index === idx
                        }
                      })
                      /* setNavList(lst) */
                    }
                  }>
                  {item.title}
                </a>
              )
            })
          }

        </div>
      </div>

      <main className={styles.main}>

        <div id="home" className={styles.con1}>
          <div className={styles.c1left}>
            <p className={styles.yi}>一</p>
            <h1 className={styles.title} text="Mission and vision">
              Mission and vision
            </h1>
            <p className={styles.desc}>
              Utilizes cutting-edge technologies to create a secure cross-chain network that enables DeFi-related innovation. We are devoted to connecting any public chains to improve the efficiency of our users' digital assets.
            </p>
          </div>

          <div className={styles.c1right}>
            <img alt="" src="/con1.png" />
          </div>
        </div>

        {/* con2 */}

        <div id="products" className={styles.con2}>
          <div className={styles.c2left}>
            <img alt="" src="/products.png" />
          </div>
          <div className={styles.c2right}>
            <h3 className={styles.c2title}>
              ZKCross is a trustworthy cross-chain protocol built with multichain zkRollup.
            </h3>
            <p className={styles.c2desc}>
              The protocol will connect with various blockchains to create a decentralized platform focused on financial products.
              ZKCross monitors and synchronizes global state changes among several blockchains by creating an omnipresent layer that sits as a cross-chain layer2. It tackles the problem of cross-chain third parties' trustworthiness by using zk-snark proofs to verify the computation and accomplish a multichain rollup.

            </p>
          </div>
        </div>

        {/* con3 */}

        <div className={styles.con3}>
          <h3 className={styles.c3title}>Technologies Highlights</h3>
          <div className={styles.c3box}>

            <div className={styles.sbox}>
              <div>
                <img alt="" src="/zk1.png" />
              </div>
              <h3>Zero-knowledge-proof</h3>
              <p>zk-snark to improve cross-chain security.</p>
            </div>

            <div className={styles.sbox}>
              <div>
                <img alt="" src="/zk2.png" />
              </div>
              <h3>Multichain zkRollup</h3>
              <p>Multichain rollup to save cost and improve scalability. </p>
            </div>

            <div className={styles.sbox}>
              <div>
                <img alt="" src="/zk3.png" />
              </div>
              <h3>Cross-chain layer2</h3>
              <p>High throughput, low gas and more possibilities, e.g. multichain NFT, cross-chain derivatives.</p>
            </div>

          </div>
        </div>

        {/* con4 */}

        <div className={styles.con4}>

          <div className={styles.c4left}>

            <div>
              <h3>
                A multichain Defi platform with similar functionalities and user experience to CEX is available.
              </h3>
              <p>
                It combines cross-chain layer 2 and multichain rollup methods to create a network that allows users to trade effectively while maintaining maximal asset control. Multichain DeFi products can also be rapidly integrated into our cross-chain layer2 network.
              </p>
              <div className={styles.leftbottom}>

                {
                  list1.map((item, index) => {
                    return <div className={styles.lbitem} key={index}>
                      <div className={styles.picbox}>
                        <img alt="" src={item.url} />
                      </div>
                      <p className={styles.txtbox}>
                        {item.txt}
                      </p>
                    </div>
                  })
                }

              </div>
            </div>

          </div>

          <div className={styles.c4right}>
            <img alt="" src="/c4.png" />
          </div>
        </div>

        {/* con5 */}

        <div className={styles.con5} id="roadmap">

          <div className={styles.c5txt}>
            <h3>Roadmap</h3>
            <p>milestones and vision for the future</p>
          </div>
          {
            !isMobile && <img alt="" src="/roadmap.png" />
          }

          {
            isMobile && <div className={styles.cell}>
              <img alt="" src="/roadmap/r1.png" />
              <img alt="" src="/roadmap/r2.png" />
              <img alt="" src="/roadmap/r1.png" />
              <img alt="" src="/roadmap/r1.png" />
            </div>
          }

        </div>

        {/* con6 */}

        <div className={styles.con6}>
          <h3 className={styles.c6top}> Partner and Investor </h3>
          <div className={styles.investorlist}>
            {
              partnerList.map((item, index) => {
                return <div className={styles.investor} key={index}>
                  <img alt="" src={item} />
                </div>
              })
            }
          </div>
        </div>

        {/* con7 */}

        <div className={styles.con7} id="about">
          <div className={styles.c7left}>
            <h3>
              INTERESTED IN FINDING
              OUT MORE
              ABOUT ZKCross?
            </h3>
          </div>
          <div className={styles.c7right}>
            <div>
              {
                c7list.map((item, index) => {
                  return <div className={styles.c7item} key={index}>
                    <div className={styles.c7itemtop}>
                      <div>
                        <img alt="" src={item.url} />
                      </div>
                      <span>{item.title}</span>
                      <img alt="" src="/arrow.png" />
                    </div>
                    <p className={styles.c7itembottom}>
                      {item.desc}
                    </p>
                  </div>
                })
              }
            </div>
          </div>
        </div>

      </main >

      <footer className={styles.footer}>
        <div className={styles.fooleft}>
          <h2>ZK CROSS</h2>
        </div>
        <div className={styles.fooright}>

          <div className={styles.contact}>
            <a href="">
              <img alt="" src="/footer/f1.png" />
            </a>
            <a href="">
              <img alt="" src="/footer/f2.png" />
            </a>
            <a href="">
              <img alt="" src="/footer/f3.png" />
            </a>
            <a href="">
              <img alt="" src="/footer/f4.png" />
            </a>
          </div>

          <div className={styles.navlist}>
            <div className={styles.navigator}>
              {
                navList.map((item, index) => {
                  return (
                    <a href={item.id}
                      key={item.id}
                      className={item.selected ? styles.active : ''}
                      onClick={
                        () => {
                          const lst = navList.map((nav, idx) => {
                            return {
                              ...nav,
                              selected: index === idx
                            }
                          })
                          /* setNavList(lst) */
                        }
                      }>
                      {item.title}
                    </a>
                  )
                })
              }
            </div>

          </div>

        </div>
      </footer>
    </div >
  )
}
